test-suites:
  captain-cli-ginkgo:
    command: nix develop --command mage test
    fail-on-upload-error: true
    output:
      reporters:
        github-step-summary:
        junit-xml: junit.xml
    results:
      path: report.xml
  captain-cli-backwards-compatibility:
    command: nix develop --command mage integrationTest
    fail-on-upload-error: true
    output:
      reporters:
        github-step-summary:
        junit-xml: junit.xml
    results:
      path: report.xml
